spring.application.name=sixt

# Sin el banner de Spring tapando el menu
spring.main.banner-mode=off

# Solo warnings y errores, asi los logs no se mezclan con la consola
logging.level.root=WARN

# Apaga Tomcat mientras la app sea solo de consola.
# Cuando empecemos con los @RestController, BORRAR esta linea.
spring.main.web-application-type=none
